<?php

namespace neomn\laraauthapi\tests;

use neomn\laraauthapi\LaraAuthApiServiceProvider;

class TestCase extends \Orchestra\Testbench\TestCase {

//    public $loadEnvironmentVariables = true;

    public function getPackageProviders($app)
    {
        return [
            LaraAuthApiServiceProvider::class,
        ];
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getEnvironmentSetUp($app)
    {

    }
}
